#Enable Logger
# Logger
logging.level:
  web: DEBUG
  '[com.bptn.weatherapp]': DEBUG
  '[org.hibernate.type]': INFO
  
# Actuator Enabled
management:
  endpoints:
    web:
      exposure:
        include: "*"
# Active Profile
spring:
  profiles:
    active: prod
# DevTools Enabled     
  devtools:
    add-properties: true
# Jackson Settings
  jackson:
    time-zone: America/Toronto
    date-format: "yyyy-MM-dd HH:mm:ss"
      
# Email Settings
  mail:
    username: obsiditeam6@gmail.com
    password: ketqpkplonaarysk
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true 
# Common Database Settings
  sql:
    init:
      continue-on-error: false
  jpa:
    show-sql: true
    open-in-view: false
    properties:  
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        '[format_sql]': true
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
---

# Default Profile
spring:
  config:
    activate:
      on-profile: default
        
# Database Settings
  datasource:
    url: jdbc:postgresql://c2-s2-t6-do-user-12484302-0.b.db.ondigitalocean.com:25060/weatherDB
    username:  doadmin
    password: AVNS_DfWDIFSiIE3vH8o4zRC
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: validate      
---

# Prod Profile
server:
  port: 8080
  
spring:
  config:
    activate:
      on-profile: prod  
  
# Database Settings
  datasource:
    url: jdbc:postgresql://c2-s2-t6-do-user-12484302-0.b.db.ondigitalocean.com:25060/weatherDB
    username: doadmin
    password: AVNS_DfWDIFSiIE3vH8o4zRC
    hikari:
      maximum-pool-size: 2  
  jpa:
    hibernate:
      ddl-auto: validate
---

# Test Profile
spring:
  config:
    activate:
      on-profile: test  
  
# Database Settings
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect